# Generated by Django 5.2.3 on 2025-06-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('remotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('code_blue', 'Code Blue'), ('motion', 'Motion'), ('sound', 'Sound'), ('nurse_call', 'Nurse Call')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remotes.remote')),
            ],
        ),
    ]
