# Generated by Django 5.2.3 on 2025-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin_clerk', 'Admin Clerk'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('patient', 'Patient')], max_length=20),
        ),
    ]
