# Generated by Django 5.2.3 on 2025-06-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('ward', models.CharField(max_length=100)),
                ('bed', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
