# Generated by Django 5.2.3 on 2025-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remote',
            name='remote_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='remote',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
