# Generated by Django 5.2.3 on 2025-06-15 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('remotes', '0002_remote_remote_id_alter_remote_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=50)),
                ('bed', models.CharField(max_length=50)),
                ('remote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remotes.remote')),
            ],
        ),
    ]
