# Generated by Django 5.2.3 on 2025-06-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_doctor_notes_doctornote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorNote',
        ),
    ]
