substitutions:
  ward: "ward3"
  bed: "bed3"
  remote_id: "${ward}_${bed}_remote"

globals:
  - id: tv_state
    type: bool
    restore_value: no
    initial_value: 'false'

esphome:
  name: ${remote_id}
  friendly_name: ${remote_id}

esp8266:
  board: d1_mini

logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${remote_id}_Hotspot"
    password: "fallback123"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: ${remote_id}
  discovery: false
  birth_message:
    topic: ${remote_id}/status
    payload: "online"
  will_message:
    topic: ${remote_id}/status
    payload: "offline"

# Button: TV Power
binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
    name: "TV Power"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: "TV button was pressed"
        - lambda: |-
            id(tv_state) = !id(tv_state);
        - mqtt.publish:
            topic: ${remote_id}/tv/state
            payload: !lambda |-
              return id(tv_state) ? "ON" : "OFF";
