esphome:
  name: antena
  friendly_name: antena

esp8266:
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5cAIiK8n7h54azNmmlflqBg7lrynp4qEw6NzF7Y1GXI="

ota:
  - platform: esphome
    password: "7c3a0f796c276d7d8bcb3b7acd206618"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Antena Fallback Hotspot"
    password: "1glHL8GWckje"

captive_portal:
    