esphome:
  name: noodles
  friendly_name:  noodles

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MXeDHNDLyCB+LBTC8wl8QS0gXgDHNbprUP8D+O/HdqQ="

ota:
  - platform: esphome
    password: "88b132a5dbf3f29893d1d1754ae8572d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Noodles Fallback Hotspot"
    password: "OSA4i4ykAQAv"

captive_portal:
    