esphome:
  name: test2
  friendly_name: test2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "E0s4UU6QDNUB13t5/ODjMgE4zIOHmWYx0kCR4YLB+LI="

ota:
  - platform: esphome
    password: "7a1186317778a0b295b7f1ace9f8c060"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test2 Fallback Hotspot"
    password: "AadovhUNsneG"

captive_portal:
    