esphome:
  name: d1minitest
  friendly_name: d1minitest

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "VU3OWcxN/obs3InJ9ytO3XHaWZcUDn1UdPW6kBcSKVM="

ota:
  - platform: esphome
    password: "ef5afba91d851ef2a699564671ce0cf7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.5.226

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1Minitest Fallback Hotspot"
    password: "cqByl6Zpnlko"

captive_portal:
    