esphome:
  name: fireb2
  friendly_name: fireB2

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "T2 Fallback Hotspot"
    password: "nqs9K4bLLP9Q"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883

# Define the GPIO pins used
binary_sensor:
  - platform: gpio
    pin: GPIO9  # Replace with your actual button pin
    name: "Push Button"
    id: button_id
    on_press:
      then:
        - switch.toggle: led_switch

output:
  - platform: gpio
    pin: GPIO18  # Replace with your actual LED pin
    id: led_output

switch:
  - platform: output
    name: "LED Switch"
    output: led_output
    id: led_switch

# SPI interface for RC522
spi:
  clk_pin: GPIO23  # SCK
  mosi_pin: GPIO22 # MOSI
  miso_pin: GPIO21 # MISO 

# RC522 RFID Reader
rc522_spi:
  cs_pin: GPIO19 # SDA / CS
  update_interval: 1s
  on_tag:
    then:
      - logger.log:
          format: "Tag detected: %s"
          args: [ 'x.c_str()' ]

sensor:
  - platform: dht
    pin: GPIO15
    model: DHT22
    temperature:
      name: "Room 1 Temperature"
      id: room1_temp
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      on_value:
        then:
          - mqtt.publish:
              topic: nursecall/room1/temperature
              payload: !lambda 'return str_sprintf("%.1f °C", x);'
    humidity:
      name: "Room 1 Humidity"
      id: room1_humidity
      unit_of_measurement: "%"
      accuracy_decimals: 1
      on_value:
        then:
          - mqtt.publish:
              topic: nursecall/room1/humidity
              payload: !lambda 'return str_sprintf("%.1f %%", x);'
    update_interval: 10s

# First run
# esphome clean fireb2.yaml
# then
# esphome run fireb2.yaml