esphome:
  name: fireb2v2
  friendly_name: fireB2v2

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "T2 Fallback Hotspot"
    password: "nqs9K4bLLP9Q"

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883
  on_message:
    - topic: theatre/light/reset
      then:
        - light.turn_off: room_light
        - logger.log: "Room light reset"
    - topic: theatre/code_blue/reset
      then:
        - light.turn_off: status_light
        - logger.log: "Code Blue state reset"
    - topic: theatre/clean/reset
      then:
        - light.turn_off: status_light
        - logger.log: "Clean state reset"
    - topic: theatre/in_use/reset
      then:
        - light.turn_off: status_light
        - logger.log: "In Use state reset"

captive_portal:
# ----------------------------
# SPI interface for RC522
# ----------------------------
spi:
  clk_pin: GPIO23  # SCK
  mosi_pin: GPIO22 # MOSI
  miso_pin: GPIO21 # MISO

# ----------------------------
# RC522 RFID Reader
# ----------------------------
rc522_spi:
  cs_pin: GPIO19  # SDA / CS
  update_interval: 1s
  on_tag:
    then:
      - logger.log:
          format: "Tag detected: %s"
          args: [ 'x.c_str()' ]
      - mqtt.publish:
          topic: nursecall/theatre/rfid
          payload: !lambda 'return x;'

# ----------------------------
# DHT22 Temperature + Humidity
# ----------------------------
sensor:
  - platform: dht
    pin: GPIO3
    model: DHT22
    temperature:
      name: "Room 1 Temperature"
      id: room1_temp
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      on_value:
        then:
          - mqtt.publish:
              topic: nursecall/room1/temperature
              payload: !lambda 'return str_sprintf("%.1f °C", x);'
    humidity:
      name: "Room 1 Humidity"
      id: room1_humidity
      unit_of_measurement: "%"
      accuracy_decimals: 1
      on_value:
        then:
          - mqtt.publish:
              topic: nursecall/room1/humidity
              payload: !lambda 'return str_sprintf("%.1f %%", x);'
    update_interval: 10s

# ----------------------------
# KY-009 RGB LED (PWM)
# ----------------------------
output:
  # RGB LED (KY-009)
  - platform: ledc
    pin: GPIO4
    id: red_pwm
  - platform: ledc
    pin: GPIO5
    id: green_pwm
  - platform: ledc
    pin: GPIO6
    id: blue_pwm

  # Dedicated Room Light Output (White LED)
  - platform: gpio
    pin: GPIO18
    id: room_light_output

light:
  - platform: rgb
    name: "Status RGB Light"
    red: red_pwm
    green: green_pwm
    blue: blue_pwm
    id: status_light

# ----------------------------
# Dedicated Room Light Output
# ----------------------------
  - platform: binary
    id: room_light
    name: "Room Light"
    output: room_light_output


# ----------------------------
# Buttons
# ----------------------------
binary_sensor:
  - platform: gpio
    pin: GPIO8
    name: "Code Blue Button"
    on_press:
      then:
        - light.turn_on:
            id: status_light
            red: 0.0
            green: 0.0
            blue: 1.0
        - mqtt.publish:
            topic: nursecall/theatre/code_blue
            payload: "triggered"
        - logger.log: "Code Blue triggered"

  - platform: gpio
    pin: GPIO16
    name: "Clean Theatre Button"
    on_press:
      then:
        - light.turn_on:
            id: status_light
            red: 0.0
            green: 1.0
            blue: 0.0
        - delay: 500ms
        - light.turn_off: status_light
        - delay: 500ms
        - light.turn_on:
            id: status_light
            red: 0.0
            green: 1.0
            blue: 0.0
        - mqtt.publish:
            topic: nursecall/theatre/clean
            payload: "needed"
        - logger.log: "Theatre marked for cleaning"

  - platform: gpio
    pin: GPIO17
    name: "Theatre In Use Button"
    on_press:
      then:
        - light.turn_on:
            id: status_light
            red: 1.0
            green: 0.0
            blue: 0.0
        - mqtt.publish:
            topic: nursecall/theatre/in_use
            payload: "yes"
        - logger.log: "Theatre marked as in use"

  - platform: gpio
    pin: GPIO14
    name: "Room Light Button"
    on_press:
      then:
        - light.toggle: room_light
        - mqtt.publish:
            topic: nursecall/theatre/light
            payload: "toggled"
        - logger.log: "Room Light Toggled"


# First run
# esphome clean fireb2.yaml
# then
# esphome run fireb2.yaml