esphome:
  name: fire3
  friendly_name: fire3

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "T2 Fallback Hotspot"
    password: "nqs9K4bLLP9Q"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883


# SPI interface for RC522
spi:
  clk_pin: GPIO23  # SCK
  mosi_pin: GPIO22 # MOSI
  miso_pin: GPIO21 # MISO 

# RC522 RFID Reader
rc522_spi:
  cs_pin: GPIO19 # SDA / CS
  update_interval: 1s
  on_tag:
    then:
      - logger.log:
          format: "Tag detected: %s"
          args: [ 'x.c_str()' ]
  
# --- Temp and Hum Sensor --
sensor:
  - platform: dht
    pin: GPIO14
    model: DHT11
    temperature:
      name: "Room Temperature"
      id: room_temp
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      on_value:
        then:
          - mqtt.publish:
              topic: nursecall/temperature
              payload: !lambda 'return str_sprintf("%.1f °C", x);'
    humidity:
      name: "Room Humidity"
      id: room_humidity
      unit_of_measurement: "%"
      accuracy_decimals: 1
      on_value:
        then:
          - mqtt.publish:
              topic: nursecall/humidity
              payload: !lambda 'return str_sprintf("%.1f %%", x);'
    update_interval: 10s
# First run
# esphome clean fireb2.yaml
# then
# esphome run fireb2.yaml