substitutions:
  ward: "ward10"
  bed: "bed10"
  remote_id: "${ward}_${bed}_remote"

esphome:
  name: ${remote_id}
  friendly_name: ${remote_id}

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.5.168 #static ip for now
    
  ap:
    ssid: "${remote_id}_Hotspot"
    password: "fallback123"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

remote_transmitter:
  pin: GPIO33
  carrier_duty_percent: 50%

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: nursecall/${remote_id}
  discovery: false
  birth_message:
    topic: nursecall/${remote_id}/status
    payload: "online"
  will_message:
    topic: nursecall/${remote_id}/status
    payload: "offline"

  on_message:
    - topic: nursecall/${remote_id}/led/nurse/set
      then:
        - lambda: |-
            if (x == "ON") id(led_nurse).turn_on();
            else id(led_nurse).turn_off();

    - topic: nursecall/${remote_id}/led/light/set
      then:
        - lambda: |-
            if (x == "ON") id(led_light).turn_on();
            else id(led_light).turn_off();

    - topic: nursecall/${remote_id}/led/volume_up/set
      then:
        - lambda: |-
            if (x == "ON") id(led_volume_up).turn_on();
            else id(led_volume_up).turn_off();

    - topic: nursecall/${remote_id}/led/volume_down/set
      then:
        - lambda: |-
            if (x == "ON") id(led_volume_down).turn_on();
            else id(led_volume_down).turn_off();

    - topic: nursecall/${remote_id}/led/channel_up/set
      then:
        - lambda: |-
            if (x == "ON") id(led_channel_up).turn_on();
            else id(led_channel_up).turn_off();

    - topic: nursecall/${remote_id}/led/channel_down/set
      then:
        - lambda: |-
            if (x == "ON") id(led_channel_down).turn_on();
            else id(led_channel_down).turn_off();

    - topic: nursecall/${remote_id}/led/tv_power/set
      then:
        - lambda: |-
            if (x == "ON") id(led_tv_power).turn_on();
            else id(led_tv_power).turn_off();

    # MQTT-based IR triggers from Home Assistant
    - topic: nursecall/${remote_id}/ir/volume_up
      then:
        - remote_transmitter.transmit_samsung:
            data: 0xE0E0E01F
        - logger.log:
            format: "IR via MQTT: Volume Up"
            level: INFO

    - topic: nursecall/${remote_id}/ir/volume_down
      then:
        - remote_transmitter.transmit_samsung:
            data: 0xE0E0D02F
        - logger.log:
            format: "IR via MQTT: Volume Down"
            level: INFO

    - topic: nursecall/${remote_id}/ir/channel_up
      then:
        - remote_transmitter.transmit_samsung:
            data: 0xE0E048B7
        - logger.log:
            format: "IR via MQTT: Channel Up"
            level: INFO

    - topic: nursecall/${remote_id}/ir/channel_down
      then:
        - remote_transmitter.transmit_samsung:
            data: 0xE0E008F7
        - logger.log:
            format: "IR via MQTT: Channel Down"
            level: INFO

    - topic: nursecall/${remote_id}/ir/tv_power
      then:
        - remote_transmitter.transmit_samsung:
            data: 0xE0E040BF
        - logger.log:
            format: "IR via MQTT: TV Power"
            level: INFO


switch:
  - platform: gpio
    pin: 2
    id: led_nurse
    name: "${remote_id} LED Nurse Call"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/nurse/state
          payload: "ON"
    on_turn_off:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/nurse/state
          payload: "OFF"

  - platform: gpio
    pin: 4
    id: led_light
    name: "${remote_id} LED Light"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/light/state
          payload: "ON"
    on_turn_off:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/light/state
          payload: "OFF"

  - platform: gpio
    pin: 5
    id: led_volume_up
    name: "${remote_id} LED Volume Up"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/volume_up/state
          payload: "ON"
    on_turn_off:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/volume_up/state
          payload: "OFF"

  - platform: gpio
    pin: 16
    id: led_volume_down
    name: "${remote_id} LED Volume Down"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/volume_down/state
          payload: "ON"
    on_turn_off:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/volume_down/state
          payload: "OFF"

  - platform: gpio
    pin: 17
    id: led_channel_up
    name: "${remote_id} LED Channel Up"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/channel_up/state
          payload: "ON"
    on_turn_off:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/channel_up/state
          payload: "OFF"

  - platform: gpio
    pin: 18
    id: led_channel_down
    name: "${remote_id} LED Channel Down"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/channel_down/state
          payload: "ON"
    on_turn_off:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/channel_down/state
          payload: "OFF"

  - platform: gpio
    pin: 19
    id: led_tv_power
    name: "${remote_id} LED TV Power"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/tv_power/state
          payload: "ON"
    on_turn_off:
      - mqtt.publish:
          topic: nursecall/${remote_id}/led/tv_power/state
          payload: "OFF"


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: "${remote_id} Button Nurse Call"
    on_click:
      then:
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/nurse
            payload: "clicked"
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/last
            payload: "nurse"
        - switch.toggle: led_nurse

  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    name: "${remote_id} Button Light"
    on_click:
      then:
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/light
            payload: "clicked"
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/last
            payload: "light"
        - switch.toggle: led_light

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "${remote_id} Button Volume Up"
    on_click:
      then:
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/volume_up
            payload: "clicked"
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/last
            payload: "volume_up"
        - switch.toggle: led_volume_up
        - remote_transmitter.transmit_samsung:
            data: 0xE0E0E01F

  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: true
    name: "${remote_id} Button Volume Down"
    on_click:
      then:
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/volume_down
            payload: "clicked"
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/last
            payload: "volume_down"
        - switch.toggle: led_volume_down
        - remote_transmitter.transmit_samsung:
            data: 0xE0E0D02F

  - platform: gpio
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
      inverted: true
    name: "${remote_id} Button Channel Up"
    on_click:
      then:
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/channel_up
            payload: "clicked"
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/last
            payload: "channel_up"
        - switch.toggle: led_channel_up
        - remote_transmitter.transmit_samsung:
            data: 0xE0E048B7

  - platform: gpio
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
      inverted: true
    name: "${remote_id} Button Channel Down"
    on_click:
      then:
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/channel_down
            payload: "clicked"
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/last
            payload: "channel_down"
        - switch.toggle: led_channel_down
        - remote_transmitter.transmit_samsung:
            data: 0xE0E008F7

  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: true
    name: "${remote_id} Button TV Power"
    on_click:
      then:
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/tv_power
            payload: "clicked"
        - mqtt.publish:
            topic: nursecall/${remote_id}/button/last
            payload: "tv_power"
        - switch.toggle: led_tv_power
        - remote_transmitter.transmit_samsung:
            data: 0xE0E040BF

text_sensor:
  - platform: mqtt_subscribe
    name: "${remote_id} Last Button Pressed"
    topic: nursecall/${remote_id}/button/last