esphome:
  name: lolinesp32
  friendly_name: lolinesp32

esp32:
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.5.230

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "T2 Fallback Hotspot"
    password: "nqs9K4bLLP9Q"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

# --- RGB LED Outputs for KY-016 ---
output:
  - platform: ledc
    pin: GPIO18  # Red
    id: red_pwm
  - platform: ledc
    pin: GPIO16  # Green
    id: green_pwm
  - platform: ledc
    pin: GPIO17  # Blue
    id: blue_pwm

# --- RGB Light using KY-016 ---
light:
  - platform: rgb
    name: "KY016 RGB LED"
    id: ky016_rgb_led
    red: red_pwm
    green: green_pwm
    blue: blue_pwm
    restore_mode: ALWAYS_OFF

# --- Buttons and PIR Sensor ---
binary_sensor:
  - platform: gpio
    pin: GPIO12
    name: "Nurse Call Button"
    on_press:
      then:
        - mqtt.publish:
            topic: "nursecall/nurse_call"
            payload: "pressed"
        - light.turn_on:
            id: ky016_rgb_led
            red: 100%
            green: 0%
            blue: 0%
    on_release:
      then:
        - light.turn_off: ky016_rgb_led

  - platform: gpio
    pin: GPIO13
    name: "Code Blue Button"
    on_press:
      then:
        - mqtt.publish:
            topic: "nursecall/code_blue"
            payload: "pressed"
        - light.turn_on:
            id: ky016_rgb_led
            red: 0%
            green: 0%
            blue: 100%
    on_release:
      then:
        - light.turn_off: ky016_rgb_led

  - platform: gpio
    pin: GPIO14
    name: "PIR Motion Sensor"
    on_press:
      then:
        - mqtt.publish:
            topic: "nursecall/movement"
            payload: "detected"
        - light.turn_on:
            id: ky016_rgb_led
            red: 0%
            green: 100%
            blue: 0%
    on_release:
      then:
        - light.turn_off: ky016_rgb_led

# --- Sound Sensor (Analog) ---
sensor:
  - platform: adc
    pin: GPIO34
    name: "Sound Sensor"
    update_interval: 1s
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 1023.0 -> 5.0
    on_value_range:
      - below: 1.0
        then:
          - mqtt.publish:
              topic: "nursecall/fall"
              payload: "detected"
      - above: 2.0
        then:
          - mqtt.publish:
              topic: "nursecall/loud_sound"
              payload: "detected"

# --- DHT22 Temperature & Humidity ---
  - platform: dht
    pin: GPIO26
    model: DHT11
    temperature:
      name: "Room Temperature"
      id: room_temp
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      on_value:
        then:
          - mqtt.publish:
              topic: nursecall/temperature
              payload: !lambda 'return str_sprintf("%.1f °C", x);'
    humidity:
      name: "Room Humidity"
      id: room_humidity
      unit_of_measurement: "%"
      accuracy_decimals: 1
      on_value:
        then:
          - mqtt.publish:
              topic: nursecall/humidity
              payload: !lambda 'return str_sprintf("%.1f %%", x);'
    update_interval: 10s

# --- SPI for RC522 RFID Reader ---
spi:
  clk_pin: GPIO23
  mosi_pin: GPIO19
  miso_pin: GPIO22
  id: bus_spi

rc522_spi:
  id: nfc_reader
  cs_pin: GPIO21
  update_interval: 1s
  on_tag:
    then:
      - logger.log: "Tag detected"
      - logger.log: "Tag UID: {{ uid }}"
      - mqtt.publish:
          topic: "rfid/tag"
          payload: "{{ uid }}"
      - text_sensor.template.publish:
          id: last_rfid_sensor
          state: !lambda 'return x;'

text_sensor:
  - platform: template
    name: "Last RFID Tag"
    id: last_rfid_sensor

# --- Buzzer Output ---
switch:
  - platform: gpio
    pin: GPIO32
    name: "Buzzer"
    id: buzzer
    on_turn_on:
      then:
        - mqtt.publish:
            topic: "nursecall/buzzer"
            payload: "on"
    on_turn_off:
      then:
        - mqtt.publish:
            topic: "nursecall/buzzer"
            payload: "off"