esphome:
  name: nodemcu
  friendly_name: NodeMCU
  
esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Rfid32 Fallback Hotspot"
    password: "JA3PKMmHSREP"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
 
# ----------------------------
# SPI interface for RC522
# ----------------------------
spi:
  clk_pin: GPIO6  # SCK
  mosi_pin: GPIO8 # MOSI
  miso_pin: GPIO7 # MISO

# ----------------------------
# RC522 RFID Reader
# ----------------------------
rc522_spi:
  cs_pin: GPIO19  # SDA / CS
  update_interval: 1s
  on_tag:
    then:
      - logger.log:
          format: "Tag detected: %s"
          args: [ 'x.c_str()' ]
      - mqtt.publish:
          topic: nursecall/theatre/rfid
          payload: !lambda 'return x;'