esphome:
  name: sensoresp
  friendly_name: sensoresp

esp32:
  board: nodemcu-32s
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.5.230

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor ESP"
    password: "Duf3pfgNJ0wB"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

# PWM Outputs for KY-016 RGB LED
output:
  - platform: ledc
    pin: GPIO5
    id: red_pwm
  - platform: ledc
    pin: GPIO16
    id: green_pwm
  - platform: ledc
    pin: GPIO17
    id: blue_pwm

# RGB Light using KY-016 LED
light:
  - platform: rgb
    name: "KY016 RGB LED"
    id: ky016_rgb_led
    red: red_pwm
    green: green_pwm
    blue: blue_pwm
    restore_mode: ALWAYS_OFF

# Buttons and Sensors
binary_sensor:
  - platform: gpio
    pin: GPIO12  # Nurse Call Button
    name: "Nurse Call Button"
    on_press:
      then:
        - mqtt.publish:
            topic: "nursecall/nurse_call"
            payload: "pressed"
        - light.turn_on:
            id: ky016_rgb_led
            red: 100%
            green: 0%
            blue: 0%
    on_release:
      then:
        - light.turn_off: ky016_rgb_led

  - platform: gpio
    pin: GPIO13  # Code Blue Button
    name: "Code Blue Button"
    on_press:
      then:
        - mqtt.publish:
            topic: "nursecall/code_blue"
            payload: "pressed"
        - light.turn_on:
            id: ky016_rgb_led
            red: 0%
            green: 0%
            blue: 100%
    on_release:
      then:
        - light.turn_off: ky016_rgb_led

  - platform: gpio
    pin: GPIO14  # PIR Motion Sensor
    name: "PIR Motion Sensor"
    on_press:
      then:
        - mqtt.publish:
            topic: "nursecall/movement"
            payload: "detected"
        - light.turn_on:
            id: ky016_rgb_led
            red: 0%
            green: 100%
            blue: 0%
    on_release:
      then:
        - light.turn_off: ky016_rgb_led

# Sound Sensor (Analog Pin A0 connected to GPIO34)
sensor:
  - platform: adc
    pin: GPIO34  # Analog input for sound sensor
    name: "Sound Sensor"
    update_interval: 1s
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 1023.0 -> 5.0
    on_value_range:
      - below: 1.0
        then:
          - mqtt.publish:
              topic: "nursecall/fall"
              payload: "detected"
      - above: 2.0
        then:
          - mqtt.publish:
              topic: "nursecall/loud_sound"
              payload: "detected"

  - platform: dht
    pin: GPIO15
    model: DHT22
    temperature:
      name: "Room 1 Temperature"
      id: room1_temp
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      on_value:
        then:
          - mqtt.publish:
              topic: nursecall/room1/temperature
              payload: !lambda 'return str_sprintf("%.1f °C", x);'
    humidity:
      name: "Room 1 Humidity"
      id: room1_humidity
      unit_of_measurement: "%"
      accuracy_decimals: 1
      on_value:
        then:
          - mqtt.publish:
              topic: nursecall/room1/humidity
              payload: !lambda 'return str_sprintf("%.1f %%", x);'
    update_interval: 10s

# RC522 RFID Configuration using SPI
spi:
  clk_pin: GPIO22  # SCK was 18
  mosi_pin: GPIO23  # MOSI
  miso_pin: GPIO19  # MISO
  id: bus_spi

# RC522 Reader
rc522_spi:
  id: nfc_reader
  cs_pin: GPIO21  # SDA/CS
  update_interval: 1s
  on_tag:
    then:
      - lambda: |-
          id(last_rfid_uid) = x;
      - text_sensor.template.publish:
          id: last_rfid_sensor
          state: !lambda 'return x;'
      - mqtt.publish:
          topic: rfid/tag
          payload: !lambda 'return x;'
      - logger.log:
          format: "Tag detected: %s"
          args: [ 'x.c_str()' ]

globals:
  - id: last_rfid_uid
    type: std::string
    restore_value: no
    initial_value: '"No tag"'

text_sensor:
  - platform: template
    name: "Last RFID Tag"
    id: last_rfid_sensor
    lambda: |-
      return id(last_rfid_uid);

# KY-012 Buzzer (Connected to GPIO32)
switch:
  - platform: gpio
    pin: GPIO32  # Buzzer
    name: "Buzzer"
    id: buzzer
    on_turn_on:
      then:
        - mqtt.publish:
            topic: "nursecall/buzzer"
            payload: "on"
    on_turn_off:
      then:
        - mqtt.publish:
            topic: "nursecall/buzzer"
            payload: "off"