esphome:
  name: t2
  friendly_name: t2

esp32:
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.5.230

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "T2 Fallback Hotspot"
    password: "nqs9K4bLLP9Q"

captive_portal:

# Onboard LED output (GPIO2)
output:
  - platform: gpio
    pin: GPIO5
    id: onboard_led_output

# Create a light from the output so we can toggle it
light:
  - platform: binary
    name: "Onboard LED"
    output: onboard_led_output
    id: onboard_led

# Toggle the light every 1s
interval:
  - interval: 1s
    then:
      - light.toggle: onboard_led