esphome:
  name: theatre-env
  friendly_name: theatre-env

esp8266:
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Theatre-Env Fallback Hotspot"
    password: "ItjapeTAS6e3"

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

sensor:
  - platform: dht
    pin: GPIO0  # or D3
    temperature:
      name: "Theatre Temperature"
      state_topic: theatre/temperature
    humidity:
      name: "Theatre Humidity"
      state_topic: theatre/humidity
    model: DHT11
    update_interval: 10s